services:
  frontend:
    image: kondasumanayana/project-1-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend


  backend:
    image: kondasumanayana/project-1-backend:latest
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy

  extractor:
    image: kondasumanayana/project-1-extractor:latest
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    command: ["rust_extractor"]

  db:
    image: kondasumanayana/postgres:13-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: bitcoin_explorer_network